# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './dialog/YTX2New_selNS.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


# from PyQt5 import QtCore, QtGui, QtGui

import PySide2.QtCore as QtCore
import PySide2.QtGui as QtGuiOrig
import PySide2.QtWidgets as QtGui
from qt_material import apply_stylesheet
import YTX2New_path_module

class Ui_YTX2New_selNS(QtGui.QDialog):
    def __init__(self, _parent=None, ns_list=[], YETI="", FILE_NS="") -> None:
        super(Ui_YTX2New_selNS, self).__init__(_parent)

        self.ns_list = ns_list
        self.MSG = "{0} 생성중 :\n".format(YETI)+\
                    "씬안에 {0} 네임스페이스를 갖고있는 alembic 이 없습니다.\n".format(FILE_NS)+\
                    "\n\n"+\
                    "[해결방법]\n"+\
                    "1. .fur 캐쉬 파일이름을 맞는 네임스페이스 번호로 변경\n"+\
                    "2. .fur 캐쉬에 적혀있는 네임스페이스 번호에 맞는 alembic 캐쉬 import"
        self.setupUi(self)
    def setupUi(self, YTX2New_selNS):
        YTX2New_selNS.setObjectName("YTX2New_selNS")
        YTX2New_selNS.resize(630, 340)
        self.horizontalLayout = QtGui.QHBoxLayout(YTX2New_selNS)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.YTX2New_info_vl = QtGui.QVBoxLayout()
        self.YTX2New_info_vl.setObjectName("YTX2New_info_vl")
        self.YTX2New_msg_lb = QtGui.QLabel(YTX2New_selNS)
        self.YTX2New_msg_lb.setObjectName("YTX2New_msg_lb")
        self.YTX2New_info_vl.addWidget(self.YTX2New_msg_lb)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.YTX2New_info_vl.addItem(spacerItem)
        self.YTX2New_btn_hl = QtGui.QHBoxLayout()
        self.YTX2New_btn_hl.setObjectName("YTX2New_btn_hl")
        self.YTX2New_ok_btn = QtGui.QPushButton(YTX2New_selNS)
        self.YTX2New_ok_btn.setObjectName("YTX2New_ok_btn")
        self.YTX2New_btn_hl.addWidget(self.YTX2New_ok_btn)
        self.YTX2New_cancel_btn = QtGui.QPushButton(YTX2New_selNS)
        self.YTX2New_cancel_btn.setObjectName("YTX2New_cancel_btn")
        self.YTX2New_btn_hl.addWidget(self.YTX2New_cancel_btn)
        self.YTX2New_info_vl.addLayout(self.YTX2New_btn_hl)
        self.YTX2New_info_vl.setStretch(0, 3)
        self.YTX2New_info_vl.setStretch(1, 1)
        self.YTX2New_info_vl.setStretch(2, 1)
        self.horizontalLayout.addLayout(self.YTX2New_info_vl)
        self.YTX2New_assetGRP_ns_view_lw = QtGui.QListWidget(YTX2New_selNS)
        self.YTX2New_assetGRP_ns_view_lw.setObjectName("YTX2New_assetGRP_ns_view_lw")
        self.YTX2New_assetGRP_ns_view_lw.addItems(self.ns_list)
        self.YTX2New_assetGRP_ns_view_lw.setCurrentRow(0)
        self.horizontalLayout.addWidget(self.YTX2New_assetGRP_ns_view_lw)
        self.horizontalLayout.setStretch(0, 3)
        self.horizontalLayout.setStretch(1, 2)
        
        self.set_link()
        self.retranslateUi(YTX2New_selNS)
        apply_stylesheet(self, YTX2New_path_module.cur_theme)
        QtCore.QMetaObject.connectSlotsByName(YTX2New_selNS)

    def retranslateUi(self, YTX2New_selNS):
        _translate = QtCore.QCoreApplication.translate
        YTX2New_selNS.setWindowTitle(_translate("YTX2New_selNS", "YTX2 - fur"))
        self.YTX2New_msg_lb.setText(_translate("YTX2New_selNS", self.MSG))
        self.YTX2New_ok_btn.setText(_translate("YTX2New_selNS", "선택"))
        self.YTX2New_cancel_btn.setText(_translate("YTX2New_selNS", "취소"))


    def set_link(self) -> None:
        self.YTX2New_ok_btn.clicked.connect(self.sel_ns)
        self.YTX2New_cancel_btn.clicked.connect(self.cancel_all)


    def get_sel_ns(self) -> str:
        return self.YTX2New_assetGRP_ns_view_lw.currentItem().text()

    def sel_ns(self) -> None:
        self.accept()


    def cancel_all(self) -> None:
        self.reject()

    


# if __name__ == "__main__":
#     import sys
#     app = QtGui.QApplication(sys.argv)
#     YTX2New_selNS = QtGui.QDialog()
#     ui = Ui_YTX2New_selNS()
#     ui.setupUi(YTX2New_selNS)
#     YTX2New_selNS.show()
#     sys.exit(app.exec_())
