# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './select_mode.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_YTX2_select_mode_wg(object):
    def setupUi(self, YTX2_select_mode_wg):
        YTX2_select_mode_wg.setObjectName("YTX2_select_mode_wg")
        YTX2_select_mode_wg.resize(400, 74)
        self.horizontalLayout = QtWidgets.QHBoxLayout(YTX2_select_mode_wg)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.YTX2_grm_mode_cb = QtWidgets.QCheckBox(YTX2_select_mode_wg)
        self.YTX2_grm_mode_cb.setObjectName("YTX2_grm_mode_cb")
        self.horizontalLayout.addWidget(self.YTX2_grm_mode_cb)
        self.YTX2_fur_mode_cb = QtWidgets.QCheckBox(YTX2_select_mode_wg)
        self.YTX2_fur_mode_cb.setObjectName("YTX2_fur_mode_cb")
        self.horizontalLayout.addWidget(self.YTX2_fur_mode_cb)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)

        self.retranslateUi(YTX2_select_mode_wg)
        QtCore.QMetaObject.connectSlotsByName(YTX2_select_mode_wg)

    def retranslateUi(self, YTX2_select_mode_wg):
        _translate = QtCore.QCoreApplication.translate
        YTX2_select_mode_wg.setWindowTitle(_translate("YTX2_select_mode_wg", "Form"))
        self.YTX2_grm_mode_cb.setText(_translate("YTX2_select_mode_wg", ".grm"))
        self.YTX2_fur_mode_cb.setText(_translate("YTX2_select_mode_wg", ".fur"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    YTX2_select_mode_wg = QtWidgets.QWidget()
    ui = Ui_YTX2_select_mode_wg()
    ui.setupUi(YTX2_select_mode_wg)
    YTX2_select_mode_wg.show()
    sys.exit(app.exec_())
