# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './dialog/fur_main_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import PySide2.QtCore as QtCore
import PySide2.QtGui as QtGuiOrig
import PySide2.QtWidgets as QtGui
# from general_md_3x import LUCY
from os import (walk, path, listdir, getcwd, chdir)
from qt_material import apply_stylesheet
import source.YTX.YTX2New_path_module as YTX2New_path_module

def get_only_folders(tar_path :str) -> list:
    return next(walk(tar_path))[1]

def find_fur_folder(tar_path :str, fur_dir_list : list) -> str:
    folder_list = get_only_folders(tar_path)
    if folder_list == []:
        return ""
    elif 'fur' in folder_list:
        fur_dir_list.append(tar_path)
        return ""
    else:
        for _folder in folder_list:
            find_fur_folder(path.join(tar_path, _folder), fur_dir_list)



def find_tasks(root_path :str) -> list:
    res_list = []

    filterted_step = ["simulation", "lighting"]

    for pipe_step in filterted_step:
        step_dir = path.join(root_path, pipe_step)
        task_list = get_only_folders(step_dir)
        for _task in task_list:
            res_list.append("{0}-{1}".format(_task, pipe_step))

    return res_list



class Ui_YTX2_fur_mw(QtGui.QMainWindow):
    close_signal = QtCore.Signal(list)
    def __init__(self, _parent=None, root_path :str="") -> None:
        super(Ui_YTX2_fur_mw, self).__init__(_parent)
        self._parent = _parent
        self.__ROOT_PATH__  = root_path
        self.__FUR_DIR__    = ""
        
        self.setupUi()
        self.init_data()
        self.set_link()


    @property
    def ROOT_PATH(self) -> str:
        return self.__ROOT_PATH__
    @ROOT_PATH.setter
    def ROOT_PATH(self, _path :str) -> None:
        self.__ROOT_PATH__ = _path

    @property
    def FUR_DIR(self) -> str:
        return self.__FUR_DIR__
    @FUR_DIR.setter
    def FUR_DIR(self, _path :str) -> None:
        self.__FUR_DIR__ = _path

    def setupUi(self):
        def move_2_center(main_view):
            qr = main_view.frameGeometry()
            cp = QtGui.QDesktopWidget().availableGeometry().center()
            qr.moveCenter(cp)
            main_view.move(qr.topLeft())

        self.setObjectName("YTX2_fur_mw")
        self.resize(652, 304)
        move_2_center(self)

        self.centralwidget = QtGui.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.YTX2_select_view_hl = QtGui.QHBoxLayout()
        self.YTX2_select_view_hl.setObjectName("YTX2_select_view_hl")
        self.YTX2_task_tw = QtGui.QTabWidget(self.centralwidget)
        self.YTX2_task_tw.setObjectName("YTX2_task_tw")
        self.YTX2_task_hl = QtGui.QWidget()
        self.YTX2_task_hl.setObjectName("YTX2_task_hl")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.YTX2_task_hl)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.YTX2_task_view_lw = QtGui.QListWidget(self.YTX2_task_hl)
        self.YTX2_task_view_lw.setObjectName("YTX2_task_view_lw")
        self.verticalLayout_2.addWidget(self.YTX2_task_view_lw)
        self.YTX2_task_tw.addTab(self.YTX2_task_hl, "")
        self.YTX2_select_view_hl.addWidget(self.YTX2_task_tw)
        self.YTX2_folder_tw = QtGui.QTabWidget(self.centralwidget)
        self.YTX2_folder_tw.setObjectName("YTX2_folder_tw")
        self.YTX2_folder_hl = QtGui.QWidget()
        self.YTX2_folder_hl.setObjectName("YTX2_folder_hl")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.YTX2_folder_hl)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.YTX2_folder_view_lw = QtGui.QListWidget(self.YTX2_folder_hl)
        self.YTX2_folder_view_lw.setObjectName("YTX2_folder_view_lw")
        self.verticalLayout_3.addWidget(self.YTX2_folder_view_lw)
        self.YTX2_folder_tw.addTab(self.YTX2_folder_hl, "")
        self.YTX2_select_view_hl.addWidget(self.YTX2_folder_tw)
        self.YTX2_version_tw = QtGui.QTabWidget(self.centralwidget)
        self.YTX2_version_tw.setObjectName("YTX2_version_tw")
        self.YTX2_version_hl = QtGui.QWidget()
        self.YTX2_version_hl.setObjectName("YTX2_version_hl")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.YTX2_version_hl)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.YTX2_version_view_lw = QtGui.QListWidget(self.YTX2_version_hl)
        self.YTX2_version_view_lw.setObjectName("YTX2_version_view_lw")
        self.verticalLayout_4.addWidget(self.YTX2_version_view_lw)
        self.YTX2_version_tw.addTab(self.YTX2_version_hl, "")
        self.YTX2_select_view_hl.addWidget(self.YTX2_version_tw)
        self.YTX2_select_view_hl.setStretch(0, 1)
        self.YTX2_select_view_hl.setStretch(1, 1)
        self.YTX2_select_view_hl.setStretch(2, 1)
        self.verticalLayout.addLayout(self.YTX2_select_view_hl)
        self.YTX2_btn_hl = QtGui.QHBoxLayout()
        self.YTX2_btn_hl.setObjectName("YTX2_btn_hl")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.YTX2_btn_hl.addItem(spacerItem)
        self.YTX2_assign_btn = QtGui.QPushButton(self.centralwidget)
        self.YTX2_assign_btn.setObjectName("YTX2_assign_btn")
        self.YTX2_btn_hl.addWidget(self.YTX2_assign_btn)
        self.YTX2_cancel_btn = QtGui.QPushButton(self.centralwidget)
        self.YTX2_cancel_btn.setObjectName("YTX2_cancel_btn")
        self.YTX2_btn_hl.addWidget(self.YTX2_cancel_btn)
        self.YTX2_btn_hl.setStretch(0, 6)
        self.YTX2_btn_hl.setStretch(1, 1)
        self.YTX2_btn_hl.setStretch(2, 1)
        self.verticalLayout.addLayout(self.YTX2_btn_hl)
        self.verticalLayout.setStretch(0, 5)
        self.verticalLayout.setStretch(1, 1)
        self.setCentralWidget(self.centralwidget)

        self.retranslateUi()
        self.YTX2_task_tw.setCurrentIndex(0)
        self.YTX2_folder_tw.setCurrentIndex(0)
        self.YTX2_version_tw.setCurrentIndex(0)

        apply_stylesheet(self, YTX2New_path_module.cur_theme)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("YTX2_fur_mw", "MainWindow"))
        self.YTX2_task_tw.setTabText(self.YTX2_task_tw.indexOf(self.YTX2_task_hl), _translate("YTX2_fur_mw", "Step 1 - Task"))
        self.YTX2_folder_tw.setTabText(self.YTX2_folder_tw.indexOf(self.YTX2_folder_hl), _translate("YTX2_fur_mw", "Step 2 - Folder"))
        self.YTX2_version_tw.setTabText(self.YTX2_version_tw.indexOf(self.YTX2_version_hl), _translate("YTX2_fur_mw", "Step 3 - Version"))
        self.YTX2_assign_btn.setText(_translate("YTX2_fur_mw", "어싸인"))
        self.YTX2_cancel_btn.setText(_translate("YTX2_fur_mw", "취소"))

    def init_data(self) -> None:
        # Set defautl path
        # task_dir = LUCY.get_pipestep_dir()
        chdir(task_dir)
        chdir("..")
        chdir("..")
        entity_dir = getcwd()
        self.ROOT_PATH = entity_dir

        # find task list
        task_list = find_tasks(self.ROOT_PATH)
        self.YTX2_task_view_lw.addItems(task_list)
        

    def set_link(self) -> None:
        self.YTX2_task_view_lw.itemClicked.connect(self.set_folder_data)
        self.YTX2_folder_view_lw.itemClicked.connect(self.set_version_data)

        self.YTX2_assign_btn.clicked.connect(self.set_assign_path)
        self.YTX2_cancel_btn.clicked.connect(self.close)


    def set_folder_data(self, item :QtGui.QListWidgetItem) -> None:
        def get_task_and_step(item_txt :str) -> list:
            return item_txt.split('-')
        
        self.YTX2_folder_view_lw.clear()


        task, pipe_step = get_task_and_step(item.text())
        

        step_dir        = path.join(self.ROOT_PATH, pipe_step, task)
        fur_dir_list    = []
        
        find_fur_folder(step_dir, fur_dir_list)

        for fur_dir in fur_dir_list:
            folder_item = QtGui.QListWidgetItem(path.basename(fur_dir))
            folder_item.setWhatsThis(path.join(fur_dir, "fur"))
            self.YTX2_folder_view_lw.addItem(folder_item)


    def set_version_data(self, item :QtGui.QListWidgetItem) -> None:
        self.YTX2_version_view_lw.clear()
        selected_fur_dir = item.whatsThis()
        ver_folder_list = listdir(selected_fur_dir)
        self.YTX2_version_view_lw.addItems(ver_folder_list)

    def set_assign_path(self) -> None:
        def get_selected_item(list_widget :QtGui.QListWidget) -> str:
            item_list = list_widget.selectedItems()
            if item_list == []:
                return ""
            return item_list[0].text()
        
        step_and_task = get_selected_item(self.YTX2_task_view_lw)
        step = step_and_task.split('-')[0]
        task = step_and_task.split('-')[0]

        fur_folder  = get_selected_item(self.YTX2_folder_view_lw)

        fur_version = get_selected_item(self.YTX2_version_view_lw)

        
        if step_and_task == "" or  fur_folder == "" or fur_version == "":
            self.close()
            return
        
        fur_dir         = self.YTX2_folder_view_lw.selectedItems()[0].whatsThis()
        self.FUR_DIR    = path.join(fur_dir, fur_version)
        
        self.close_signal.emit([self.FUR_DIR, self._parent])
        self.close()



# if __name__ == "__main__":
#     import sys
#     app = QtGui.QApplication(sys.argv)
    
#     ui = Ui_YTX2_fur_mw()
#     ui.show()

#     sys.exit(app.exec_())



